name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests (if any)
        run: npm run test -- --coverage --passWithNoTests
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: fAVJg5qW277gRXwmakGsynh8
          vercel-org-id: team_TiwXcPSyI7dNY4otv8dPNsRp
          vercel-project-id: prj_WlhACDwGpnke1KIe1d46FxkCX5E3
          
      - name: Deploy to Vercel (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
            vercel-token: fAVJg5qW277gRXwmakGsynh8
            vercel-org-id: team_TiwXcPSyI7dNY4otv8dPNsRp
            vercel-project-id: prj_WlhACDwGpnke1KIe1d46FxkCX5E3
            vercel-args: '--prod' 